salesforcecli/plugin-release-management

messages/circleci.json
messages/repositories.json
messages/trust.sign.json
package.json
src/codeSigning/packAndSign.ts
src/commands/circleci/envvar/update.ts
src/commands/circleci/index.ts
src/commands/repositories/index.ts
src/commands/trust/sign.ts
src/repositories.ts
src/repository.ts
test/codeSigning/packAndSign.test.ts
test/commands/circleci.envvar.update.test.ts
test/commands/circleci.test.ts
test/commands/repositories.test.ts
yarn.lock

Adds three new commands:
* `repositories`: list known repositories
* `circleci`: list known circleci slugs (gets from repositories)
* `circleci:envvar:update`: updates envvars on circleci projects
And a flag:
* `trust:sign --tarpath`: allows to sign a tgz incase the signing job fails but the package is uploaded
@W-8449512@ @W-8449490@

feat: add 3 new commands and a new flag

---

src/repository.ts

fix: exclude merge commits when determinin if release is necessary

---

src/commands/npm/lerna/release.ts
src/commands/npm/package/release.ts
src/commands/typescript/update.ts
src/repository.ts

Strips comments from tsconfig.json before parsing
@W-8775832@

fix: strip tsconfig comments before parsing as JSON

---

.eslintrc.js
README.md
command-snapshot.json
messages/cli.versions.inspect.json
package.json
src/commands/cli/versions/inspect.ts
yarn.lock

Adds a `cli:versions:inspect` command so that we can quickly verify that all install paths have the same version
```
~/code/plugin-release-management [mdonnalley/versions-inspect] : bin/run cli:versions:inspect --help
inspect the CLI version across all install paths
USAGE
$ sfdx cli:versions:inspect -c <string> -l <string> [-d <string>] [-s] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]
OPTIONS
-c, --channels=legacy|stable|stable-rc|latest|latest-rc                           (required) the channel you want to inspect (for achives, latest and latest-rc are
translated to stable and stable-rc. And vice-versa for npm)
-d, --dependencies=dependencies                                                   glob pattern of dependencies you want to see the …
```

feat: add cli:versions:inspect command

---

src/package.ts
src/repository.ts

Runs the `version` (if available) command during release
@W-8920199@

feat: run version script

---

command-snapshot.json
messages/npm.package.release.json
src/commands/npm/lerna/release.ts
src/commands/npm/package/release.ts
src/commands/typescript/update.ts
src/repository.ts
test/repository.test.ts

Exposes the prerelease option on standard version to bump the [prerelease (build) number](https://semver.org/#spec-item-9).
@W-8913121@

feat: use prerelease

---

src/repository.ts

fix: lerna release

---

src/repository.ts

Run scripts in the package directory

fix: run scripts in package directory

---

CHANGELOG.md
README.md
package.json
src/commands/typescript/update.ts
src/repository.ts

It handles typescript upgrade in lerna repos by looking into every package in the packages glob array in the `lerna.json` configuration file.
@W-9024415@

feat: handle lerna repo

---

src/repository.ts

fix: do not use release-as during prerelease

---

src/repository.ts

fix: prerelease

---

src/codeSigning/upload.ts

Add a proxy agent to the S3 connection
@W-0@

fix: add proxy support for aws upload

---

src/codeSigning/upload.ts

s3 api takes an agent object, not an array of gent objects
@W-0@

fix: s3 does not take an array of agents

---

src/codeSigning/upload.ts
test/registry.test.ts
yarn.lock

add httpOption to s3 proxy agent
@W-0@

fix: try to get proxy to s3 to work

---

src/codeSigning/upload.ts
test/registry.test.ts
yarn.lock

This reverts commit 2f83adac64cb450fbda6e770c148d4a215a37c3b.
@W-0@

Revert "fix: try to get proxy to s3 to work (#210)"

---

src/codeSigning/upload.ts
test/registry.test.ts
yarn.lock

Add httpOptions agent for S3 proxy
@W-8712510@

fix: add httpOptions agent entry for s3

---

src/commands/dependabot/automerge.ts

support the other variant of github token env var
@W-9477765@

fix: some of our projects use GH_TOKEN, some GITHUB_TOKEN

---

src/repository.ts

Add --registry parameter to sfdx-trust callout
@W-8712510@

chore: add registry param to sfdx-trust calls

---

src/commands/npm/lerna/release.ts
src/commands/npm/package/release.ts

Writing .npmrc needs be above the first step that interacts with NPM.
@W-0@

fix: move write of npmrc files up

---

src/commands/npm/package/promote.ts

Writes the npm token to the `.npmrc` file before running any npm commands

fix: write npmrc file before promote

---

src/package.ts

Supports tagging pinned dependencies, e.g.
```
pinnedDependencies: [
"@salesforce/plugin-config@sf"
]
```
The specified tag will be used instead of the tag provided by the `--tag` flag. This is helpful for `sf` releases where we want to pin most of the dependencies to `latest` but will have some plugins that are using a different tag - most notably `plugin-config` which will be using `sf` instead of `latest`

feat: allow pinned dependencies to be tagged

---

src/package.ts

Warns and skips if any `pinnedDependency` isn't also specified in the `dependencies` section in the package.json

fix: warn and skip any pinned deps that are not in package.json

---

package.json
src/package.ts
test/package.test.ts

Made changes in the functionality to check whether the next version is available or not.
@W-9496922@

chore: modified retrieve npm package functionality

---

package.json
src/package.ts
test/package.test.ts

Reverts salesforcecli/plugin-release-management#262

Revert "chore: modified retrieve npm package functionality"

---

src/dependencies.ts
src/repository.ts
test/dependencies.test.ts
test/repository.test.ts

Replaces `sfdx-trust` with `plugin-trust`.
@W-9496922@

fix: replace sfdx-trust with plugin-trust

---

src/commands/cli/install/test.ts

fix: test that sf is installed alongside sfdx

---

command-snapshot.json
messages/cli.releasenotes.json
src/commands/cli/releasenotes.ts
src/package.ts

Adds `sf-release cli:releatenotes` command
```
~/repos/salesforcecli/plugin-release-management [mdonnalley/release-notes] : bin/run cli:releasenotes --help
pull all relevant information for writing release notes.
USAGE
$ sfdx cli:releasenotes -c <string> [-s <string>] [-m] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]
OPTIONS
-c, --cli=sf|sfdx                                                                 (required) the cli to pull information for
-m, --markdown                                                                    format the output in markdown
-s, --since=since                                                                 the version number of the previous release. Defaults to the latest-rc version on npm
--json …
```

feat: add command to pull info for release notes

---

src/package.ts

Fixes logic around retrieving npm package

fix: npm package retrieve

---

package.json
test/pluginCommand.test.ts
yarn.lock

@W-9960315@
Bumps ocilif to v2

fix: bump oclif to v2

---

src/commands/cli/install/test.ts
src/package.ts

relace old cli-ux imports with oclif/core
@W-0@

fix: replace old cli-ux imports

---

package.json
src/commands/cli/versions/inspect.ts
yarn.lock

use ensureArray from kit
@W-11590594@

refactor: ensureArray from kit

---

src/commands/channel/promote.ts

fix: bugs around sha and platform

---

src/commands/cli/release/build.ts

Sets the correct `head` for PRs

Set correct PR head

---

package.json
src/amazonS3.ts
src/commands/channel/promote.ts
src/commands/cli/install/test.ts
src/commands/cli/tarballs/verify.ts
src/commands/cli/versions/inspect.ts
src/commands/repositories/index.ts
src/dependencies.ts
src/package.ts
yarn.lock

Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@

feat: use latest oclif/core

---

package.json
src/commands/cli/tarballs/smoke.ts
src/package.ts
yarn.lock

Adds smoke tests for JIT plugin installation

feat: smoke tests for JIT plugins

---

src/commands/dependabot/automerge.ts

automerges dev-scripts bumps that are all-green and up-to-date
QA: 
you can probably QA it on this repo, or anything else with an open devScripts PR (try on some non-mergeable ones, too?)

feat: automerge dev-scripts updates when green

---

src/commands/cli/tarballs/smoke.ts

fix: run JIT smoke tests serially

---

src/commands/cli/tarballs/verify.ts

remove checks for sfdx related to plugin-generator

fix: remove plugin-generate check

---

src/commands/cli/tarballs/smoke.ts

Only run JIT smoke tests for the main executable

fix: only run JIT smoke tests for main executable

---

messages/cli.release.build.json
src/commands/cli/release/build.ts

Allow adding labels to Release PRs. This will be used to set a label for nightly automerges
[@W-12506482@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12506482)

Add labels to release PR

---

messages/cli.release.build.json
src/commands/cli/release/build.ts

Allows you to designate what channel this PR is intended for. This channel will get picked up by GHA to support: latest-rc, latest, nightly, and prereleases
[@W-12599588@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12599588)

Add intended release channel

---

src/commands/cli/release/build.ts

Fixes a check for when to add the release description to the PR body
[@W-12599588@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12599588)

Add pr description logic

---

src/commands/cli/release/build.ts

Trying to create patches from PRs (with the `release-it`) label was causing too many issues. Going back to an early idea that ends up being much more simple. Whenever we are creating a patch or prerelease we will create a branch based off of the “starting point” (`--start-from-github-ref` or `--start-from-npm-dist-tag`) to use as the PR base. Now GHA actions will be watching for merges into the `release-base/*` branches just like it does for main. 
Here are some examples of created PRs when running this locally. No flags change so this should not need any changes to the PR creation scripts in `sfdx-cli` and `cli`. It will however require a few changes to [create-cli-release.yml](https://github.com/salesforcecli/sfdx-cli/blob/main/.github/workflows/create-cli-release.yml). Working on that …

fix: adds base branch for patches

---

src/commands/cli/tarballs/smoke.ts

Attaches cause to smoke test error 

fix: add error to cause

---

src/commands/cli/tarballs/smoke.ts

Batches `--help` smoke tests to hopefully prevent this command form getting killed in github actions 
[@W-12994874@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12994874)

fix: throttle help smoke tests

---

command-snapshot.json
src/commands/cli/release/automerge.ts

fix: check GH token exists at runtime

---

package.json
yarn.lock

Bumps @oclif/core and @salesforce/sf-plugins-core to latest versions to resolve this issue in the sf tests: https://github.com/salesforcecli/cli/actions/runs/6051888935/job/16424262198?pr=1094

fix: bump core and sf-plugins-core

---

src/jit.ts

Parallelize JIT install tests
@W-14122700@

feat: parallelize jit tests

---

src/commands/cli/tarballs/prepare.ts

Updates PRM to delete unused jsforce v2 files.

fix: remove unused jsforce stuff

---

package.json
src/repository.ts
test/repository.test.ts
yarn.lock

the top-level CLI release process uses the removed code to increment the package.json file.
https://github.com/salesforcecli/cli/actions/runs/8593538072/job/23545172892

fix(ci): restore standardVersion stuff for cli publish scripts

---

src/commands/cli/artifacts/compare.ts

log which plugin is causing the problem
https://github.com/salesforcecli/cli/actions/runs/9179780384/job/25243066746?pr=1680#step:6:12

feat: log additional info for json parse errors

---

src/commands/cli/release/automerge.ts

Increase the `per_page` amount of the `check_runs` api request to ensure that we get all the checks

fix: request more check_run results

---

src/commands/cli/artifacts/compare.ts

https://github.com/salesforcecli/cli/actions/runs/9311914087/job/25631848769?pr=1699

fix: more attemps at npm view json workaround

---

package.json
src/commands/channel/promote.ts
src/commands/dependabot/automerge.ts
src/commands/github/check/closed.ts
src/commands/npm/dependencies/pin.ts
src/commands/repositories/index.ts
tsconfig.json
yarn.lock

update new table.
@W-16736201@
issue: alias property was not in the pkg data table. (src/commands/npm/dependencies/pin.ts)

feat: update new table

---

package.json
src/commands/cli/release/automerge.ts
src/commands/dependabot/automerge.ts
yarn.lock

Bumps octokit dependencies to latest
@W-17868231@

W-17868231 - fix: bump octokit dependencies

---

src/amazonS3.ts

Paginates the results from `listObjectsV2` so that we can list more than 1000 results. 
We were having issues with the promote step not finding the version in the objects returned
Before: 
After:
[@W-18039502@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18039502)

W-18039502 paginates listObjectsV2
