salesforcecli/plugin-release-management

- messages/npm.dependencies.pin.json
- src/commands/npm/dependencies/pin.ts
- src/package.ts
- test/commands/dependencies.pin.test.ts
adds the `npm:dependencies:pin` command to take entries in the `pinnedDependencies` package.json to pin them to the latest, or specified via flag, version 
```
npm:dependencies:pin                                    
Name                     Version  Tag
───────────────────────  ───────  ──────
@salesforce/core         2.15.4   latest
@salesforce/plugin-auth  1.4.5    latest
```
or when targeting a specific tag
```
npm:dependencies:pin --tag test                         
Name                     Version  Tag
───────────────────────  ───────  ──────
@salesforce/core         2.15.4   latest
@salesforce/plugin-auth  0.0.6    test
```
> fix: add ability to pin deps to specified version @W-8222552@

- README.md
- messages/npm.dependencies.pin.json
- messages/typescript.update.json
- src/commands/typescript/update.ts
- src/package.ts
- src/repository.ts
- test/package.test.ts
- test/repository.test.ts
- Adds `typescript:update` command which does the following:
- updates typescript version to latest
- updates ES target to ESNext
- installs dependencies
- runs tests
- renames `ProjectJson` interface to `PackageJson`, which is more accurate
@W-8667963@
> feat: add typescript:update command

- src/commands/typescript/update.ts
Updates `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to `latest` when testing updated version of typescript
@W-8667867@
> fix: update @typescript-eslint packages when testing new ts version

- src/commands/npm/lerna/release.ts
- src/commands/npm/package/release.ts
- src/commands/typescript/update.ts
- src/package.ts
- src/registry.ts
- src/repository.ts
- test/registry.test.ts
- test/repository.test.ts
Added a env var, NPM_REGISTRY, that allows users to select which npm
registry is to be used for install and publish actions.
Gives the user the ability to direct certain actions to a specific npm registry by setting env var NPM_REGISTRY.
> feat: 🎸 @W-8712470@ add env var for target registry

- src/repository.ts
Uses the `Repository.execCommand` method to run `git push` so that an error is thrown if it fails
@W-8820867@
> fix: throw error if git push fails

- src/commands/cli/versions/inspect.ts
Fixes `cli:versions:inspect` so that stable doesn't incorrectly download stable-rc
> fix: use correct stable channel

- src/repository.ts
> fix: stage changes to README before the commit

- src/repository.ts
- test/repository.test.ts
Fixes `npm:lerna:release` by removing the `yarn run version` step (since lerna will run that for us anyways)
> fix: lerna release

- src/repository.ts
Adds the `prerelease` flag to the standard-version command used during the prepare step
> fix: add prerelease flag when preparing for publish

- src/repository.ts
Lerna publish will fail if it doesn't define the `packages` property in the lerna.json. It should provide the right default so it works without this value.
N/A
> fix: lerna publish to use correct default package dir [skip-validate-pr]

- command-snapshot.json
- package.json
- src/commands/npm/release/validate.ts
- src/commands/typescript/update.ts
- src/inspectCommits.ts
- src/package.ts
- src/repository.ts
- test/package.test.ts
- test/repository.test.ts
Adds `npm:release:validate` so that we can programmatically determine if a release should happen earlier in the build
```
sfdx npm:release:validate
true
```
```
sfdx npm:release:validate --json
{
status: 0,
shouldRelease: true
}
```
```
sfdx npm:release:validate --json --verbose
{
status: 0,
shouldRelease: true,
packages: [
{
name: '@salesforce/plugin-auth',
currentVersion: 1.5.3,
releaseableCommits: [ // list of commits that will warrant a new release
{ type: 'feat', body: 'add a new feature' }
],
unreleaseableCommits: [], // list of commits that do not warrant a new release
shouldRelease: true
}
]
}
```
@W-9234354@
> feat: add npm:release:validate command

- command-snapshot.json
- messages/dependabot.consolidate.json
- package.json
- src/commands/dependabot/consolidate.ts
- src/package.ts
- test/repository.test.ts
- yarn.lock
Adds `dependabot:consolidate`
I **do not** think we should incorporate this command into our monthly checklist. I would prefer to start auto-merging minor/patch dependabot PRs. However, this is still a nice tool to have around 
```
~/code/plugin-release-management [mdonnalley/dependabot-consolidate] : bin/run dependabot:consolidate --help
consolidate dependabot PRs into a single PR
USAGE
$ sfdx dependabot:consolidate -m major|minor|patch -b <string> -t <string> [--ignore <array>] [-d] [--no-pr] [-o <string>] [-r <string>] [--json] [--loglevel
trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]
OPTIONS
-b, --base-branch=base-branch                                                     (required) [default: main] name of the base branch for merging
-d, --dryrun …
```
> feat: add command for consolidating dependabot PRs

- command-snapshot.json
- messages/npm.package.promote.json
- src/commands/npm/package/promote.ts
- src/package.ts
Adds an `npm:package:promote` command for promoting canary releases to latest. This is a requirement for plugin-functions,  which needs to have a canary release. Their flow will look something like this:
* merge all PRs into a canary branch
* a merge into the canary branch will trigger a new release under their canary tag
* once they're ready, they will merge the canary branch into the `main` branch
* the merge into `main` will promote the canary release to `latest` (instead of publishing a new version)
This command essentially wraps around the [npm dist-tag add](https://docs.npmjs.com/cli/v7/commands/npm-dist-tag) command but it adds a few helpful features:
* verifies that the `NPM_TOKEN` is a publishing token since automation tokens don't have the ability to manipulate tags
* ensures …
> feat: add npm:package:promote command

- src/commands/dependabot/automerge.ts
What does this PR do? [repeat attempt]
merges one green, up-to-date-with-main dependabot PR of the specified maximum version bump
the intended use of this command is to run nightly on a repo from the orb
What issues does this PR fix or reference?
@W-9457889@
> fix: forgot to load the messageDir

- command-snapshot.json
- messages/npm.lerna.release.json
- messages/npm.package.release.json
- src/commands/npm/lerna/release.ts
- src/commands/npm/package/release.ts
Adds a verify flag to lerna and package release cmds with allowNo.
Defaults to true and when --no-verify will skip post publish availability check and digital signature verifications
@W-8750717@
> fix: add verify flag

- command-snapshot.json
- messages/cli.tarballs.prepare.json
- messages/cli.tarballs.verify.json
- messages/cli.versions.inspect.json
- package.json
- src/commands/cli/tarballs/prepare.ts
- src/commands/cli/tarballs/verify.ts
- src/commands/cli/versions/inspect.ts
- tsconfig.json
* Adds a `cli:tarballs:prepare` command to replace the [clean-for-tarballs script in sfdx-cli](https://github.com/salesforcecli/sfdx-cli/blob/main/scripts/clean-for-tarballs). This is required for the `sf` release job 
* Adds a `cli:tarballs:verify` command to replace the [verify-tarballs script in sfdx-cli](https://github.com/salesforcecli/sfdx-cli/blob/main/scripts/verify-tarballs). This is required for the `sf` release job
[](url)
```
~/code/sfdx-cli [main] : ~/code/plugin-release-management/bin/run cli:tarballs:prepare --help
remove unnecessary files from node_modules
USAGE
$ sfdx cli:tarballs:prepare [-d] [-t] [--verbose] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]
OPTIONS
-d, --dryrun …
```
> Adds commands to support sf release build

- src/commands/cli/tarballs/prepare.ts
- src/commands/cli/tarballs/verify.ts
- src/commands/npm/dependencies/pin.ts
- src/package.ts
- test/commands/dependencies.pin.test.ts
- fixes the `cli:tarball:*` commands to support sf releases
- updates `npm:dependencies:pin` to support aliased npm packages
> feat: support sf releases

- src/commands/npm/package/release.ts
Put the `Push Changes to Git` stage in a finally block in case signing verification fails
> fix: push to github even if signing verification fails

- src/commands/npm/lerna/release.ts
- src/commands/npm/package/release.ts
Use `plugins:trust:verify` instead of `trust:plugin:verify` 
@W-9904081@
> fix: use correct command to verify signed plugin

- command-snapshot.json
- messages/dependabot.automerge.json
- src/commands/dependabot/automerge.ts
Adds `--skip-ci` flag to `dependabot:automerge` so that we can avoid building new releases for `sf`
@W-9910648@
> feat: add --skip-ci flag to automerge

- .circleci/config.yml
- command-snapshot.json
- messages/cli.install.json
- package.json
- src/commands/cli/install/test.ts
- yarn.lock
Adds `cli:install:test` which will eventually be used to test install availability across all supported install paths (both sf and sfdx)
See this [CircleCI job](https://app.circleci.com/pipelines/github/salesforcecli/plugin-release-management/1638/workflows/2b14db55-8895-4de0-a18a-babb51cacc37) for an example
```
~/repos/salesforcecli/plugin-release-management [mdonnalley/cli-install-test] : bin/run cli:install:test --help
install sf or sfdx
USAGE
$ sfdx cli:install:test -c <string> -m <string> [--channel <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]
OPTIONS
-c, --cli=sf|sfdx                                                                 (required) the cli to install
-m, --method=installer|npm|tarball …
```
> feat: add cli:install:test command

- src/commands/cli/versions/inspect.ts
Removes the check that prevented inspecting the `stable-rc` channel for the `sf` cli.
@W-0@
> fix: allow verifying stable-rc channel for sf

- src/commands/cli/latestrc/build.ts
- Use `[skip-validate-pr]` to skip the validation for the PR created by `cli:latestrc:build`
> fix: properly skip pr validation

- command-snapshot.json
- messages/cli.tarballs.smoke.json
- package.json
- src/commands/cli/schemas/collect.ts
- src/commands/cli/tarballs/smoke.ts
- yarn.lock
Adds `cli:tarballs:smoke` to replace existing smoke tests ([sf](https://github.com/salesforcecli/cli/blob/main/package.json#L132) and [sfdx](https://github.com/salesforcecli/sfdx-cli/blob/main/package.json#L222))
```
~/repos/salesforcecli/plugin-release-management [mdonnalley/smoke-test] : bin/run cli:tarballs:smoke --help
smoke tests for the tarballed CLI
USAGE
$ sfdx cli:tarballs:smoke -c <string> [--verbose] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]
OPTIONS
-c, --cli=sf|sfdx                                                                 (required) the cli to install
--json                                                                            format output as json
--loglevel=(trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERR …
```
> feat: add cli:tarballs:smoke

- src/commands/cli/latestrc/build.ts
Only set `git config user.email` and `git config user.name` if they are not already set. This prevents the command from overwriting the git config on your personal machine
@W-10205989@
> fix: only set git config if does not exist

- src/commands/cli/tarballs/verify.ts
Allow any file under `scripts` to be included in the tarball
@W-10121246@
> fix: allow any script to be included in tarball

- src/commands/cli/install/test.ts
Removes the expectation that `sf` will be installed alongside `sfdx` for npm installs
Depends on https://github.com/salesforcecli/sfdx-cli/pull/351
> fix: remove expectation that sf will exist alongside sfdx npm installs

- src/commands/npm/release/validate.ts
- src/inspectCommits.ts
- src/package.ts
- test/inspectCommits.test.ts
- test/package.test.ts
Updates `npm:release:validate` to fail if a major version bump is detected. 
Once this is merged, any major version bump will need to be done manually in the package.json
@W-10203815@
> Do not allow automatic major version bumps

- LICENSE.txt
- command-snapshot.json
- messages/dependabot.automerge.json
- src/commands/dependabot/automerge.ts
Adds `--merge-method` flag to the `dependabot:automerge` command so that PRs can be merged in repos with merge commit option disabled.
GH docs: https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request
@W-0@
> feat: add --merge-method flag to automerge

- src/commands/dependabot/automerge.ts
Removes ref to an invalid flag (typo) that was causing `merge_method: undefined` in the payload even with `--merge-method squash`. 
@W-0@
> fix: remove invalid flag reference for `merge-method`

- command-snapshot.json
- messages/cli.latestrc.build.json
- src/commands/cli/latestrc/build.ts
Provides option in `cli:latestrc:build` to skip bumping either the resolutions or the pinned dependencies
> feat: optionally skip resolutions and pinnedDeps in latestrc build

- src/package.ts
Updates `Package.nextVersionIsHardcoded` to handle scenario where a package hasn't been released yet.
> fix: handle scenario where no versions exist yet

- .circleci/config.yml
- .gitignore
- command-snapshot.json
- messages/cli.install.test.json
- src/amazonS3.ts
- src/commands/cli/install/test.ts
- Updates `cli:install:test` to write to a .json file instead of supporting --json. This makes CI much better since you can see all the logs while still having a way to parse json results
- Test for `sf` on `sfdx` installer tests
- Report failure when npm or aws are not available
@W-10293558@
> Improve install tests

- src/repository.ts
Stop relying on `npx` for executing `git` commands
> fix: stop using npx for git commands

- bin/dev
- bin/dev.cmd
- package.json
- src/commands/cli/schemas/collect.ts
- yarn.lock
This makes sure that paths are normalized after `fg` returns them so that the `cli schemas collect` command will work on Windows.
N/A
[[skip-validate-pr]]
> fix: allow collecting plugin schemas on Windows

- command-snapshot.json
- messages/cli.latestrc.build.json
- src/commands/cli/latestrc/build.ts
- src/package.ts
- test/package.test.ts
Allows the build-latest-rc script to *only* update the packages that are passed to the `--only` flag. This is especially useful for `patch` releases
[@W-11462358@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11462358)
> `--only` flag for the build-latest-rc command

- src/commands/dependabot/automerge.ts
repos with skippable checks (ex: [sandbox nuts](https://github.com/salesforcecli/plugin-org/actions/runs/3105185768/jobs/5030500396)) aren't automerging because my previous code insisted all checks be complete and successful. 
This allows skipped checks in the "is it passing" decision
@W-11584724@
> feat: allow skipped checks automerge

- src/commands/cli/release/build.ts
Updates `cli release build` command to always set `base` to `main` when creating a PR.
When creating a patch release, the command was setting the `base` field to the RC branch, causing the GH API to fail (it tries to create a PR using the same branch as `head` and `base`).
GH API docs: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
> fix(rc): set `base` to `main` when creating a PR

- src/commands/cli/release/build.ts
Will not delete remote branch if you are running this command with `--build-only`
[@W-12376135@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12376135)
> Don't delete remote branch if build-only

- src/commands/cli/release/build.ts
We often have Type conflicts in our Release builds because of slightly different versions of libraries. Usually running `npx yarn-deduplicate` will fix these issues by getting all plugins using the same library versions (as long as it satisfies semver)
The problem is, `sf-compile` will run as a post-install script. It often throws Type errors and stops our Release builds since it runs before we have a chance to deduplicate dependencies. 
With this change the flow will be:
- Run **just** an install first with `--ignore-scripts` 
- Run `npx yarn-deduplicate` to remove deps
- Run another [standard] install to install deduped deps and run all pre/post install scripts
> Dedup before scripts

- src/commands/cli/tarballs/smoke.ts
Makes wrapper around `execSync` print the error message of the spawned process when it fails.
> fix: don't swallow `execSync` error

- src/commands/cli/release/build.ts
Some output was getting lost in the `cli:release:build` script when errors were thrown. Some error details exist on `stdout` instead of the `error.message`. When `child_process.exec` is promisified, the `stdout` and `stderr` are added to the err object ([highlight link to docs](https://nodejs.org/api/child_process.html#:~:text=execute%20the%20command.-,If%20this%20method%20is%20invoked%20as%20its%20util.promisify()ed,the%20callback%2C%20but%20with%20two%20additional%20properties%20stdout%20and%20stderr.,-const%20util%20%3D)). We can log the additional error detail from `error.stdout` to get better output in Github Actions
Before: https://github.com/salesforcecli/sfdx-cli/actions/runs/4050136185/jobs/6967228421#step:12:55
After:
[@W-12467974@](https://gus.my.salesforce.com/apex/ADM_WorkLoca …
> Always log stdout

- messages/cli.artifacts.compare.json
- src/commands/cli/artifacts/compare.ts
- src/commands/cli/release/build.ts
- src/commands/cli/schemas/collect.ts
- src/commands/cli/schemas/compare.ts
- Ensures that plugins are pinned before doing artifacts comparison
- Deprecates `cli:schemas:collect` and `cli:schemas:compare`
- Deprecates `schema` and `snapshot` flags on `cli:release:build`
> feat: ensure plugin versions are pinned before comparing artifacts

- src/commands/cli/releasenotes.ts
- src/commands/cli/tarballs/smoke.ts
Ensure that the correct package.json path is used for verifying plugin install
> fix: use correct path for verifying install

- src/commands/cli/versions/inspect.ts
- Adds support for the `nightly` channel on `cli:versions:inspect`
- Adds the Apple silicon (`arm64`) tarballs to the list for validation ([our docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux))
- ~~Changes a few logs to errors. The command will throw after logging the results, may as well fail early~~
[@W-12632139@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12632139)
> fix: adds nightly channel, adds arm64 tars

- src/commands/cli/artifacts/compare.ts
The `sf` v2 beta revealed a bug in the `cli:artifact:compare` logic. Updated the version lookup to find the closest "less-than" semver version.
Failing build:
https://github.com/salesforcecli/cli/actions/runs/4792981346/jobs/8525014876?pr=709#step:6:10
QA:
> Correctly find the closest previous version

- command-snapshot.json
- messages/cli.release.build.json
- src/commands/cli/release/build.ts
Allows us to set the base branch for generated PRs. This will not be used often, but is handy for certain situations such as long running "nightlies" on prerelease branches. 
[@W-13120638@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13120638)
> Add a 'pr-base-branch' flag

- command-snapshot.json
- messages/cli.install.jit.test.md
- messages/cli.tarballs.smoke.json
- package.json
- src/commands/cli/install/jit/test.ts
- src/commands/cli/tarballs/smoke.ts
- src/jit.ts
- yarn.lock
Add separate command for JIT tests, `sf-release cli:install:jit:test`
@W-14096048@
> feat: add JIT tests

- src/jit.ts
Prevents the oclif.lock refresh from happening. 
We have integration tests for that in `@oclif/plugin-plugins` [here](https://github.com/oclif/plugin-plugins/blob/main/test/integration/sf.integration.ts)
Testing this locally it went from 10m31s to 6m8s. 
This should make a significant difference on windows which currently take between 30-35 minutes ([example](https://github.com/salesforcecli/cli/actions/runs/6227941306/job/16903919583))
[@W-14122700@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14122700)
> fix: prevent lock refresh

- command-snapshot.json
- messages/cli.install.jit.test.md
- package.json
- src/commands/cli/install/jit/test.ts
- src/jit.ts
Adds `--jit-plugin` flag to specify which tests you want to test the install
QA:
- Pull branch
- `yarn build`
- cd to your local `cli` (sf) dir
- Run `../plugin-release-management/bin/run cli:install:jit:test --jit-plugin "@salesforce/plugin-community" -j @salesforce/plugin-env`
- Confirm that only those two plugins are tested
- Confirm files exist at `ls -lah $TMPDIR/sf-jit-test/@salesforce`
- Next run without the flag, and make sure all plugins install.
[@W-14169311@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14169311)
> Adds jit-plugin flag

- src/commands/cli/release/build.ts
- src/jit.ts
- Use `bin/run.js` for JIT test if `bin/run` doesn't exist
> fix: support bin/run.js

- src/commands/cli/artifacts/compare.ts
treat missing `flag` or `alias` properties on a snapshot as `[]`.
https://github.com/salesforcecli/cli/actions/runs/8089988440
> fix: prevent empty flags/aliases

- src/codeSigning/packAndSign.ts
Safely fail `revertPackageJsonIfExists` in `packageAndSign.ts` if the backup package.json doesn't exist (which was the [original design](https://github.com/salesforcecli/plugin-release-management/commit/99b534e3ac3278e19cbbe8928ed917f95168160c#diff-d51f800de2ce90f984d5fc649ca4433587383e05c86e0a6f60732e7ab56076aaL203)). Fixes issue with [failing publishes](https://github.com/salesforcecli/plugin-apex/actions/runs/8250889022/job/22566653180).
> fix: safely fail package.json revert

- src/commands/cli/artifacts/compare.ts
becasue of https://github.com/npm/cli/issues/7537
handle both json and non-json responses for npm view 
https://github.com/salesforcecli/cli/actions/runs/9289440974/job/25563341138?pr=1695
> feat: handle non-json from npm view

- command-snapshot.json
- messages/cli.versions.inspect.md
- schemas/cli-versions-inspect.json
- src/codeSigning/SimplifiedSigning.ts
- src/commands/cli/versions/inspect.ts
- src/commands/dependabot/automerge.ts
- src/package.ts
Removes `sfdx` from the cli:version:inspect command
Other cleanup to remove complexity
Example of this skipping non-existing tarballs:
Testing:
- pull branch
- yarn build
- Run the same command we use during promotions [here](https://github.com/salesforcecli/cli/blob/e86babd2842de2bc55c4123833185db6e94f4b51/.github/workflows/promote-rc-to-latest.yml#L56)
- `bin/run.js cli:versions:inspect -c stable-rc -l archive`
- You can run it with `npm` also if you want 
- `bin/run.js cli:versions:inspect -c stable-rc -l archive -l npm`
NOTE: I did not look at any of the "dependency" listing code. That was out of scope for this.
[@W-16893140@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16893140)
> Removes `sfdx` from the cli:version:inspect command
